CREATE TABLE IF NOT EXISTS `slo`.`slodata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` LONGTEXT NULL DEFAULT NULL,
  `title` LONGTEXT NULL DEFAULT NULL,
  `headerh1` LONGTEXT NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `dv` LONGTEXT NULL DEFAULT NULL,
  `htmlcontent` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
